### ISSUE TITLE
Remove Bento Box and Article Integration (epic)

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1137]
**Requirements**

As a user I want to:
- [ ] Go *either* to locally indexed collections *or* to Articles.
- [ ] Want a single, unambiguous advanced search in each search area.
- [ ] Want consistent, intuitive facets in the local search.
- [ ] Want facets organized more intuitively.

As Web Librarian I want to:
- [ ] Separate Articles search from local search
- [ ] Present local search and articles search unambiguously on the web page

This requirement comes out of the Usability Study (see #1145). The study recommends removing the bento box and separating the article search from the main discovery search. The core requirements of this issue are:

- [x] Remove bento controller and views
- [ ] Remove EDS gem and helpers
- [ ] Remove EDS advanced-search controller and views
- [ ] Clean up routes to reflect absent bento and EDS functions.

On the website side, we will need to design a new link to EDS for article searching. We could also consider dropping EDS entirely, and presenting an EBSCOhost link for Article searching (CSU would have to be consulted on whether the content was comparable) - this would be down the road.

These changes are currently being considered by WAT. @nnunn is working on wireframes for approval (and can include them in this issue when approved). 

A lot of issues will be closeable when we de-integrate Article search:
#1126 
#1091 
#1066 
#697 
#442 
#425 
#1107 
#1057 
#1056 
#993 
#929 
#911 
#649 
#415 
#414 
#151
#412
#413
#577

**Comment by redlibrarian** [comment]
Update: Since the release of the Discovery usability report, we have decided to remove the bento box and the articles integration, so this issue is obsolete. (Leaving open until our meeting this afternoon).

**Comment by redlibrarian** [comment]
We might be able to change this issue to "remove EDS gem and integration".

**Comment by weiweishi** [comment]
Article search is still in place but the UI changes on bento has been completed. Closing the ticket.
