### ISSUE TITLE
Main Results of Usability Study (epic)

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1145]
Based on the recently-completed [usability study](https://docs.google.com/document/d/167lR6oku3Axttw6PgdSj5GXRS7-hMNoVAy5yeRgAsn8/edit) we want to accomplish the following:

- [x] Remove bento view
- [x] Reword "search everything" (out of discovery project scope)
- [x] Add separate article-search to home page (out of discovery project scope)
- [ ] Retain search terms between simple and advanced search
- [ ] Develop "search within" functionality (may be out of scope)
- [ ] Fix e-resource access usability (out of scope)
- [ ] Update record views and functionality (including "more like this")
- [ ] Reorder and relabel facets

**Comment by redlibrarian** [comment]
I think these individual pieces can/should be captured in more specific issues, then we can dispense with this.

**Comment by weiweishi** [comment]
We will need further investigation on requirements for other usability recommendations - closing the ticket for now.
