### ISSUE TITLE
No Loan/RCRF/BPSC forms

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1149]
**Requirements**

As a user I want to:
- [ ] View non-requestable/non-loanable material held in Bruce Peel Special Collections, the Archives, or are microform or newspapers.
- [ ] Select where I want to view the material (RCRF or BPSC) (for BPSC and Archives material)
- [ ] Make an appointment to view the material (for RCRF and BPSC material)
- [ ] Request the material to particular location (for newspapers and microforms)
- [ ] Autopopulate bib-record information into the form. 

As Bruce Peel Special Collections staff I want to:
- [ ] Receive an email notifying me of the item to be viewed (for BPSC material)
- [ ] Receive an email containing the contact information of the user
- [ ] Have the material routed to BPSC for viewing (for Archives/RCRF material)

As Archives/RCRF staff I want to:
- [ ] Receive an email notifying me of the item to be viewed (for Archives/RCRF material)
- [ ] Receive an email containing the contact information of the user

As Access Services staff I want to:
- [ ] 

We will have to flesh out these requirements with CJ (Access Services) and Robert Desmarais/Linda Quirk (BPSC).

Current BPSC form: http://bpsclibrarynews.blogspot.ca/2017/11/retrieval-request-form.html
Current BARD/Archives form: https://docs.google.com/forms/d/e/1FAIpQLSfSIP8XC3lr-EhPCByRG5OrrSm8ZOd7fy8lQ2BJUW-kn7gB7Q/viewform
RCRF request form: https://web.library.ualberta.ca/catalogue/bard/

We'll need Balsamiq screenshots to complete the requirements of this issue.

Changes to the RCRF form.
* Pickup location: change name to "viewing location". (BPSC and RCRF Reading Room).
* Cleanup preamble language (redundant when we have the forms integrated).
* Add text for micro/newspapers (please indicate volume, issue, dates for the item you require - put this text above additional notes and remove individual volume, issue, dates fields).
* For micro/newspapers: pickup locations can stay the same (though bring it up to date). BPSC and RCRF don't have to be in this list.
* Change contact line to "for any assistance, please call".
* Change name of RCRF form to "RCRF Depository Request Form".

For BPSC and RCRF material, email goes to Depository team with CC to viewing location (BPSC and Archives reading room). 

Email addresses: bardreq@ualberta.ca (add alias depository@ualberta.ca); for viewing location of RCRF reading room -> archives email address.

READONSITE / holdable logic.
Can we CC the initial email into a Google Spreadsheet for staff to keep track of requests.Depository staff mark as "shipped", BPSC staff mark as "returned".

**Comment by redlibrarian** [comment]
- [ ] Add BSJ and Augustana as RCRF READONSITE location.

**Comment by redlibrarian** [comment]
Scott HS library has a micro room, so micro requests need to be sent to ILL and to Scott.
