### ISSUE TITLE
Evaluate and Add New Collections (Epic).

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1161]
**Requirements**

As a user I would like to:
- [ ] Search multiple collections at once
- [ ] Search collections beyond the library catalogue

As the Discovery Librarian I would like to:
- [ ] Make undiscoverable collections discoverable
- [ ] Make them available through a single search tool

As a metadata/cataloguing staff-member I would like to:
- [ ] Ensure new collections are properly mapped
- [ ] Ensure relevant fields are indexed for search/display (respecting semantics)

We have decided that we will add the Kule Folklore Collection (#957 ), which is a collection of MARC records, as part of the Summer 2018 project. We would also like to add one non-MARC collection. We will work with the metadata team to determine which collection it would be best to add this summer. The current candidates are:
- William C Wonders (#1042)
- Curriculum (#958)
- Linguistics (#959)
- Microguides (#1054)

However, there may be / are other candidates for this, as this list is quite old now. We will work with the metadata and bib services team to determine a good non-MARC candidate for this summer. Any new collection will require an ingest pipeline to be built, so we will have to work with ops on that. In addition, some of these collections (e.g. Microguides) may require update interfaces to be built, as they are collections which are being updated on an ongoing basis.

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
