### ISSUE TITLE
Discovery: BPSC Request Form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1184]
**High-level user story**
As a user of the Discovery service, I want to be able to send a request to the Bruce Peel Special Collections to view non-requestable/non-loanable materials held there. It needs to allow me to:
- Select where I want to view the material (RCRF or BPSC)
- Notify BPSC staff with my contact information so that they can contact me and book an appointment with me for me to come in and view the material
- Autopopulate bib-record information into the form.

**Current situation**
Currently, when the user sees a non-loanable/non-requestable item, they can't take any action on the item to proceed with a request. 
![image](https://user-images.githubusercontent.com/2047614/41866353-1bcf595a-786d-11e8-90aa-84f7fd44c5a8.png)

There are two types of materials that can be requested at BPSC:
- Monographs/Books 
- Archival materials (currently about 12 archival collections, but numbers will be actively increasing as they have staff working in this area)

BPSC currently has two forms, one for requesting monographs/books: https://docs.google.com/forms/d/126ZJ6r6L42AeoWVyOQRWdY9b0SYv7VxUljx6V1d56Po/viewform?edit_requested=true
one for requesting archival materials:  https://docs.google.com/forms/d/1-L6cAek91koI7lU5_4j6kpp_4-AUYIhETM26Xjg1uEw/viewform?edit_requested=true

Archival collections have the finding aid link on their MARC record, that differentiating them from regular BPSC objects. 
https://neos.library.ualberta.ca/uhtbin/cgisirsi/?ps=RkqsM66Ulk/UAARCHIVES/67260015/123

This information should be part of the API response from Symphony, but it is not presented on the Discovery record. 

The list of current available archival collections is on the Discover Archives Retrieval Request Form (Bruce Peel Special Collections) form. 

Both forms are Google Forms, which gives the BPSC staff a spreadsheet to help them track the requests. 

**Detailed requirements**

- Add the "Request Me" button on an object that has a "ReadOnSite" status, and belongs to Bruce Peel Special Collection. 
![screenshot from 2018-06-25 11-52-14](https://user-images.githubusercontent.com/2047614/41867013-1eced8f4-786f-11e8-971b-a11ded7d192d.png)
- Required fields on the form:
  - Name/Email of the person who sends the request
  - appointment time for the viewing
- For monograph/book materials (the majority of the requests), the form should be populated with title and call number of the object. An additional optional field should be a free-text field for other information so that the form can be used outside the discovery workflow. 
- For archival collection materials, the form should be populated with the collection name. An additional required field is the item number in their finding aid. An alternative solution could be the "Request Me" button links to the Discover Archives finding aid link. 

- Language on the request form can remain the same. A wireframe needs to be created and provide to Linda Quirk. 
- **New**: Request form should be sent to bpscrequest@ualberta.ca
- To have a way to keep track of the requests similar to the spreadsheet that offers by Google Forms. 
   
**Priority**
Request form for the Monography/Books.

**Comment by redlibrarian** [comment]
Description of the finding aid link problem: https://github.com/ualbertalib/discovery/issues/877

**Comment by redlibrarian** [comment]
@weiweishi I think the adding the link to the holdings table like that is a good solution.

**Comment by murny** [comment]
Before we can close these request form issues, here's a list of small things that need to get addressed:

- [ ] Need a group email created for BPSC On Site Request Form to replace personal emails (https://github.com/ualbertalib/discovery/issues/1259#issuecomment-436862926)
- [ ] Remove Feature Flag
- [ ] Decision about if Call Number is required or not on BSPC On Site Request Form (#1404)

**Comment by seanluyk** [comment]
@murny I added the group email to the user story above

**Comment by seanluyk** [comment]
I can confirm that this works in the latest version in prod

**Comment by murny** [comment]
That's good 👍. It's still under a feature flag though, so once everyone is happy with it, we can remove the feature flag and have this available to everyone

**Comment by seanluyk** [comment]
@murny I think there is some work on the receiving end of the emails that @weiweishi was going to do with BPSC and RCRF so we can get started on testing. Otherwise I think we're very close with this

**Comment by murny** [comment]
Sounds great!

**Comment by seanluyk** [comment]
Done, closing.
