### ISSUE TITLE
[Discovery] More complete feature test suite

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1330]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to make changes, or do updates and I'm not confident that I've checked every possible regression, or even know what all the features are to test.

**Describe the solution you'd like**

Results
- [x] Shield/logo to represent UofA holdings
- [x] Google book jackets
- [x] Metadata for symphony holdings includes Author, format, publication year, copies owned by
- [x] Metadata for ejournals and databases is more limited.
- [x] By default 25 results are displayed.
- [x] Many more facets

Record View
- [x] Go to bookmarks (#1562)
- [x] Send a correction (#1727)
- [x] View search history (#1725)
- [x] Text me (Canadian SMS) / email me (#1722)
- [x] Journal records contain proper metadata (#1704)
- [x] Chained subject linking (#1708)
- [x] Author link on record view page search for the author (#1710)
- [x] Content presented in the holding table is proper (#1712)

Databases and ejournals Record View
- [x] Usage rights in the holding table (#1712)
- [ ] Coverage information (blocked by #1473)
- [x] A tiny link to ILL (#1740)

Search Result
- [X] Create feature tests for the search result page: https://github.com/ualbertalib/discovery/issues/1600

Logging (tests will be implemented in #423)
- [ ] errors in logs
- [ ] deprecations in logs

Fix blacklight/spec/rails helper https://github.com/ualbertalib/discovery/pull/1464#discussion_r248857540

Many of these customizations are identified in this report: https://docs.google.com/document/d/1VTeu4ZYfLhbLWsznRqFBU0qccQhD17J83tW6LDQu7OY/

**Describe alternatives you've considered**
Continue to test manually and have low confidence when deploying.

**Comment by seanluyk** [comment]
@pgwillia this is really fantastic, I fully support this work given our current deployment issues

**Comment by murny** [comment]
NOTE: as part of this ticket we need to get off ingesting tons of objects into solr on every time you run the tests? You don't need thousands of objects to test the code. 

As a result this makes the tests take far longer then they should be (rspec itself takes no time at all to run (since we only have 75 tests), but this ingestion process takes 3 times longer then the actual rspec process). And also this makes debugging travis difficult because of the spam the ingestion creates and as a result you can't see anything in travis about the actual tests: 
![image](https://user-images.githubusercontent.com/1930474/47525740-39e91400-d85b-11e8-901e-dd6d288356b1.png)

**Comment by weiweishi** [comment]
We will move adding test for the logging to #423. Remaining work:
- [ ] a tiny link to ILL.
