### ISSUE TITLE
Solr Relevancy Epic

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1499]
**Is your feature request related to a problem? Please describe.**
Data passing through the Discovery architecture is a black box to most of us.  There are some issues that @seanluyk has been collecting about relevancy:
https://docs.google.com/document/d/123osY1nFFQmUJX7jTVz72PcY6O5cbK1MCYa4XPhWVPo/edit

**Describe the solution you'd like**
- [x] These to be better understood.  
- [x] More clearly documented.
- [ ] Improved and intuitive for users.

**Comment by pgwillia** [comment]
This is a summary of what I've found about mapping of data within discovery
https://docs.google.com/spreadsheets/d/18bNfP3gE2zdorVpGbGCNNTTrSirrRNGjtpT72zWdVhk/edit?usp=sharing

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/discovery/issues/1309
https://github.com/ualbertalib/discovery/issues/1508

**Comment by pgwillia** [comment]
This long running process is re-running logs against the new Solr configs to check for unexpected changes.
![Screenshot from 2019-04-30 09-55-34](https://user-images.githubusercontent.com/1220762/56975482-28483800-6b2e-11e9-8563-8f2cb5b4157d.png)

**Comment by pgwillia** [comment]
Can also parse the log for visualizations

![Screenshot from 2019-05-23 15-25-12](https://user-images.githubusercontent.com/1220762/58287903-71775a80-7d6f-11e9-919d-7ec88b9bb37d.png)

**Comment by seanluyk** [comment]
@pgwillia very cool, this is going to be really handy going forward!
